codecov:
  require_ci_to_pass: yes
  notify:
    after_n_builds: 3

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: 80%
        threshold: 2%
        if_ci_failed: error

    patch:
      default:
        target: 70%
        threshold: 5%

  ignore:
    - "test/**/*"
    - "scripts/**/*"
    - "node_modules/**/*"

comment:
  layout: "header, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes

flags:
  unittests:
    paths:
      - contracts/
    carryforward: true
